### ISSUE TITLE
Replace `Vendor.php` file

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/wp-plugin#13]
If we are going to use a vendor lets use the one from composer instead there is no reason two have 2 vendors

**Comment by adamf321** [comment]
We can replace this with something like the Inc/API file from Skaled.
It was originally intended to initiate all the vendor modules by calling their init() functions.

**Comment by mitogh** [comment]
Yes or we can use a hook like `admin_init` or something from PSR4 to do it more easy.

**Comment by adamf321** [comment]
Do you mean we can run the Endpoints's init() functions automatically, @mitogh? 
That's the point of this file, if we can automate it then great! However, we'll still an API (or Routes) file to customise the /routes endpoint for each project.

**Comment by mitogh** [comment]
Yes I mean we can have a file similar like that in each project instead of having a vendor file I'm going to work in an PR to see if we can use that.
