### ISSUE TITLE
Move ACF fields from PHP to JSON

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/wp-plugin#28]
**Steps to reproduce and a minimal demo of the problem**

List ACF fields modules

**Current behavior**

There are some problems or issues with this approach: 
- At the moment we are including manually PHP ACF fields. 
- We need to verify CI on this ACF Files.
- We can't edit a group from the admin UI of ACF.

**Expected/desired behavior**
- Remove files from the code base or PHP
- Enable edit from the admin

**Other information**

This can be solved with the following: 

``` php
add_filter('acf/settings/save_json', function(){
    return LEEANP_PLUGIN_DIR . 'acf';
});
add_filter('acf/settings/load_json', function($paths){
    unset($paths[0]);
    $paths[] = LEEANP_PLUGIN_DIR . 'acf';
    return $paths;
});
```

Also we need to create an  `acf` directory. This will:
- Save all groups that we create under the `acf` dir.
- We can avoid to fix CI issues or load things from the JSON file.
- Automatic sync.
- Able to edit the group from the admin UI.

**Comment by adamf321** [comment]
So the workflow is:
1. Create/edit the group with the editor
2. Save it. It is automatically written to JSON.
3. Commit and push your changes.

Is that right? If so, this is much nicer than what we have now!

**Comment by mitogh** [comment]
Pretty much.

we avoid the time to create new classes since save and sync is automatic.
