### ISSUE TITLE
Add plugins to composer

### ISSUE THREAD

**Issue by adamf321** [moxie-lean/wp-plugin#39]
**Steps to reproduce and a minimal demo of the problem**

**Current behavior**
Some plugins missing which we always use

**Expected/desired behavior**
Add:

```
"moxie-lean/acf-gravity-forms-select": "*",
"wpackagist-plugin/acf-image-crop-add-on": "*"
```

And update scripts

```
"install-wordpress-seo": "cd ./wp-content/plugins/wordpress-seo && composer install",
    "install-gravity-forms-select": "cd ./wp-content/plugins/acf-gravity-forms-select && composer install && composer update",
    "post-install-cmd": "@install-gravity-forms-select && @install-wordpress-seo",
    "post-update-cmd": "@install-gravity-forms-select"
```

**Other information**

**Comment by mitogh** [comment]
Closing this one here since this should be implemented in the generators instead of here.

https://github.com/moxie-lean/generators/issues/34
