### ISSUE TITLE
Fix composer script for Yoast

### ISSUE THREAD

**Issue by adamf321** [moxie-lean/wp-plugin#40]
**Steps to reproduce and a minimal demo of the problem**
Activate WordPress SEO plugin

**Current behavior**
Error: http://snaps.getmoxied.net/1d3V431s3D18

**Expected/desired behavior**
Activates successfully

**Other information**
I think there's something wrong with the script in composer.json.

**Comment by zzuga** [comment]
If I remember correctly, we were fetching the plugin from a git repository and this needs calling composer to build it.

If we pull it from wpackagist instead it works fine. You can see it working in the STX project.
