### ISSUE TITLE
Add plugins only for production

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/wp-plugin#45]
**Steps to reproduce and a minimal demo of the problem**

Run composer install

**Current behavior**

At the moment all plugins are installed on development and production

**Expected/desired behavior**

Only plugin required for development should be installed on development and only plugins for production like `wp-stream` should be installed on production.

We can just update the type of required dependencies.

**Comment by mitogh** [comment]
Related with #39

**Comment by adamf321** [comment]
Actually... I think we should leave the same list in prod and dev, because it will help with debugging. Eg if you need to copy production to local to run some tests, you should have exactly the same plugins running (what if Stream was causing the issue?)

**Comment by mitogh** [comment]
Yes this is not a removal of plugins is just an optional step, you can install all plugins if you want that's why there are `dev` and `production` dependencies.

You can install all or just the ones from one group only.

**Comment by mitogh** [comment]
Closing this one as well since should be implemented in other place instead of here: 

https://github.com/moxie-lean/generators/issues/35
