### ISSUE TITLE
Missing required plugins and Service temporarily unavailable

### ISSUE THREAD

**Issue by n8finch** [moxie-lean/wp-plugin#53]
**Steps to reproduce and a minimal demo of the problem**
Using `yo moxie-lean:new-wp-plugin` or cloning from the repo, I get the same behavior on my local WordPress install. I'm running VVV with a basic install, no plugins but Moxie's and the WP REST API v2.

**Current behavior**
Whether using `yo moxie-lean:new-wp-plugin`, or cloning from the repo, when I activate the plugin, I get an admin notice: `There are missing required plugins, please review.`: http://prntscr.com/cay1z8

My local base URL is `http://moxie.dev/`. If I check `http://moxie.dev/wp-json/lean/v2/routes`, I find that the `Service temporarily unavailable`: http://prntscr.com/cay3mm

However, if I deactivate the plugin and check standard WP REST API routes, they show up: http://prntscr.com/cay3tc

My permalinks are set to `/blog/%postname%`

If I reactivate the plugin and then install the front end with `git clone https://github.com/moxie-lean/ng-web-app` and follow the rest of the instructions to npm start, I get an Internal Server Error: http://prntscr.com/cay47i

**Expected/desired behavior**
I assume the expected behavior is that routes will show up and the ecosystem just works (I actually don't really know what to expect:-)). 

**Other information**
I'm really excited about this framework, and hoping I can get this figured out. I'll also keep working on this on my end. Cheers, and all the best!

**Comment by mitogh** [comment]
Hey @n8finch thank you for taking the time, the plugin relies on: 
- https://www.advancedcustomfields.com/pro/ to create some logic I'm going to keep this open in order to make sure you can use the plugin even without the ACF plugin. 

Let me know if you have any questions.

Thank you.

**Comment by n8finch** [comment]
Hey there @mitogh! Thanks for letting me know that ACFPro is required. That fixed the issue, and now I've got the `Hello World` up. 

Cheers! Looking forward to digging into this.

**Comment by mitogh** [comment]
No problem at all please let me know if you have any feedback is appreciated to improve the adoption of this.

Thank you
