### ISSUE TITLE
PHP consts can't be defined dynamically 

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/wp-plugin#9]
Replace with instance/static variables instead.

https://github.com/moxie-leean/wp-plugin/blob/master/PluginSetup.php#L9-L12

**Comment by adamf321** [comment]
Why?

**Comment by mitogh** [comment]
Is how PHP works, you need to set a literal value on a const.

**Comment by mitogh** [comment]
> The value must be a constant expression, not (for example) a variable, a property, or a function call.

[Ref](http://php.net/manual/en/language.oop5.constants.php)

**Comment by adamf321** [comment]
I think you can define them with another constant, eg const FIVE_WEEKS = 5 \* WEEK_IN_SECONDS;

It was working ok like this on my localhost at least

**Comment by mitogh** [comment]
It creates a PHP warning: 

```
<?php

define('WEEK_IN_SECONDS', 604800);

class  A {
  const FIVE_WEEKS = 5 * WEEK_IN_SECONDS;
}

var_dump( A::FIVE_WEEKS );
```

It creates a `Parse error: . on PHP 5.6 < 

And the plugin has PHP 5.4 as the PHP version used. 

This can be used on PHP 5.6.0. not in lower versions.

**Comment by adamf321** [comment]
What version runs on our servers?

**Comment by mitogh** [comment]
PHP 5.6.18

**Comment by adamf321** [comment]
Ok. Well we could update the min php version. But either way it's not a big deal for me.

**Comment by mitogh** [comment]
Closing this one already updated on https://github.com/moxie-lean/wp-plugin/commit/c58aeeae21f39c202b08d42341634bd71644818d
